ALTER TABLE plan_contents
    ADD COLUMN IF NOT EXISTS unit_amount BIGINT,
    ADD COLUMN IF NOT EXISTS cost_unit VARCHAR(20),
    ADD COLUMN IF NOT EXISTS cost_quantity INT,
    ADD COLUMN IF NOT EXISTS per_person_share BIGINT,
    ADD COLUMN IF NOT EXISTS cost_source VARCHAR(20);
