ALTER TABLE wishes ADD COLUMN IF NOT EXISTS lcls_system1_code VARCHAR(20);
ALTER TABLE wishes ADD COLUMN IF NOT EXISTS lcls_system2_code VARCHAR(20);
ALTER TABLE wishes ADD COLUMN IF NOT EXISTS lcls_system3_code VARCHAR(20);
